name: prosperity3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - pip
  - jsonpickle
  - pip:
    - prosperity4btest
    - streamlit
    - plotly
    - watchdog